/**
 * AUTO-GENERATED TYPES - DO NOT EDIT MANUALLY
 *
 * Generated by: npm run gen-types:typescript
 *
 * To regenerate:
 * 1. Ensure SUPABASE_PROJECT_ID is set in .env.local
 * 2. Run: npm run gen-types:typescript
 *
 * This file will be overwritten on each generation.
 * For custom type aliases, use ./types.ts instead.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          user_id: string
          display_name: string
          primary_tz: string
          language: string
          created_at: string
        }
        Insert: {
          user_id: string
          display_name: string
          primary_tz: string
          language?: string
          created_at?: string
        }
        Update: {
          user_id?: string
          display_name?: string
          primary_tz?: string
          language?: string
          created_at?: string
        }
        Relationships: []
      }
      metrics: {
        Row: {
          id: number
          user_id: string
          name: string
          description: string | null
          type: 'boolean' | 'rating' | 'number' | 'select' | 'tags' | 'notes'
          emoji: string | null
          direction: 'positive' | 'negative'
          is_required: boolean
          order_index: number
          config: Json
          archived_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: number
          user_id: string
          name: string
          description?: string | null
          type: 'boolean' | 'rating' | 'number' | 'select' | 'tags' | 'notes'
          emoji?: string | null
          direction: 'positive' | 'negative'
          is_required?: boolean
          order_index?: number
          config?: Json
          archived_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: number
          user_id?: string
          name?: string
          description?: string | null
          type?: 'boolean' | 'rating' | 'number' | 'select' | 'tags' | 'notes'
          emoji?: string | null
          direction?: 'positive' | 'negative'
          is_required?: boolean
          order_index?: number
          config?: Json
          archived_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      daily_checkin: {
        Row: {
          user_id: string
          day_id: string
          status: 'draft' | 'submitted'
          completion_pct: number
          created_at: string
          updated_at: string
        }
        Insert: {
          user_id: string
          day_id: string
          status: 'draft' | 'submitted'
          completion_pct?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          user_id?: string
          day_id?: string
          status?: 'draft' | 'submitted'
          completion_pct?: number
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      metric_entry: {
        Row: {
          user_id: string
          metric_id: number
          day_id: string
          bool_value: boolean | null
          int_value: number | null
          float_value: number | null
          text_value: string | null
          select_key: string | null
          tag_keys: string[] | null
          created_at: string
          updated_at: string
        }
        Insert: {
          user_id: string
          metric_id: number
          day_id: string
          bool_value?: boolean | null
          int_value?: number | null
          float_value?: number | null
          text_value?: string | null
          select_key?: string | null
          tag_keys?: string[] | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          user_id?: string
          metric_id?: number
          day_id?: string
          bool_value?: boolean | null
          int_value?: number | null
          float_value?: number | null
          text_value?: string | null
          select_key?: string | null
          tag_keys?: string[] | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'metric_entry_metric_id_fkey'
            columns: ['metric_id']
            referencedRelation: 'metrics'
            referencedColumns: ['id']
          }
        ]
      }
      push_subscriptions: {
        Row: {
          id: number
          user_id: string
          endpoint: string
          p256dh: string
          auth: string
          user_agent: string | null
          created_at: string
          last_seen_at: string | null
        }
        Insert: {
          id?: number
          user_id: string
          endpoint: string
          p256dh: string
          auth: string
          user_agent?: string | null
          created_at?: string
          last_seen_at?: string | null
        }
        Update: {
          id?: number
          user_id?: string
          endpoint?: string
          p256dh?: string
          auth?: string
          user_agent?: string | null
          created_at?: string
          last_seen_at?: string | null
        }
        Relationships: []
      }
      reminder_settings: {
        Row: {
          user_id: string
          reminder_time: string
          enabled: boolean
          created_at: string
        }
        Insert: {
          user_id: string
          reminder_time: string
          enabled?: boolean
          created_at?: string
        }
        Update: {
          user_id?: string
          reminder_time?: string
          enabled?: boolean
          created_at?: string
        }
        Relationships: []
      }
    }
    Views: Record<string, never>
    Functions: {
      save_day: {
        Args: {
          p_user_id: string
          p_day_id: string
          p_status: string
          p_entries: Json
        }
        Returns: {
          completion_pct: number
          saved_count: number
        }
      }
    }
    Enums: Record<string, never>
  }
}

// Helper type for accessing table rows
export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row']

// Helper type for accessing table inserts
export type TablesInsert<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert']

// Helper type for accessing table updates
export type TablesUpdate<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update']
